server:
  port: 9411

spring:
  application:
    name: zipkin-server
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
